#server:
#  error:
#  include-message: always
#  include-binding-errors: always

spring:
  datasource:
    username: root
    password: c!!2211paKev
    url: jdbc:mysql://localhost:3306/reception_db
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
#      ddl-auto: update
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect