spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/super_market_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true

    username: root
    password: c!!2211paKev
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect

    hibernate:
      ddl-auto: update

    open-in-view: false

    properties:
      hibernate:
      format_sql: true
