spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://localhost:3306/demo180402021_db?createDatabaseIfNotExist=true&useSSL=false
  username: root
  password: c!!2211paKev

jpa:
  hibernate.ddl-auto: update
  generate-ddl: true
  show-sql: true